#!/usr/bin/env python

# Import our facebook python SDK
import facebook
import json # Grab our JSON lib too

# Define our Facebook Access Token
access_token = '***REMOVED***'

# Define our "thank you" message
thankyou_message = 'Thank you! (I may have just written this comment from a script...)'

# Define our ridiculous "birthday" query
birthday_fql = "SELECT post_id, actor_id, target_id, created_time, message FROM stream WHERE source_id = me() AND filter_key = 'others' AND created_time > 1359810000 AND actor_id != 600269293 AND ( strpos(message, 'birthday') >= 0 OR strpos(message, 'Birthday') >= 0 OR strpos(message, 'happy') >= 0 OR strpos(message, 'Happy') >= 0 ) LIMIT 200"

# Create a new GraphAPI instance with our access token
graph = facebook.GraphAPI(access_token)

# Grab our birthday posts using our FQL query
birthday_posts = graph.get_object('fql', q=birthday_fql)

# Let's loop through all of our returned posts
for post in birthday_posts['data']:
	# Grab the post's ID
	post_id = post['post_id']

	# "Like" the post
	graph.put_object(post_id, 'likes')

	# "Like" the post
	graph.put_object(post_id, 'comments', message=thankyou_message)

	# Print to keep track
	print 'The like/comment should have posted'

# Let's get this "likes" steez going
